### ISSUE TITLE
I keep on getting errors

### ISSUE THREAD

**Issue by Zrp200** [rubysl/rubysl-forwardable#1]
```
/home/travis/.rvm/gems/ruby-2.0.0-p598/bundler/gems/rubysl-forwardable-4a76567d99e8/lib/rubysl/forwardable/forwardable.rb:121: warning: method redefined; discarding old debug
/home/travis/.rvm/gems/ruby-2.0.0-p598/bundler/gems/rubysl-forwardable-4a76567d99e8/lib/rubysl/forwardable/forwardable.rb:121: warning: method redefined; discarding old debug=
/home/travis/.rvm/gems/ruby-2.0.0-p598/bundler/gems/rubysl-forwardable-4a76567d99e8/lib/rubysl/forwardable/forwardable.rb:192:in `module_eval': /home/travis/.rvm/gems/ruby-2.0.0-p598/bundler/gems/rubysl-forwardable-4a76567d99e8/lib/rubysl/forwardable/forwardable.rb:183: syntax error, unexpected '.' (SyntaxError)
          .__send__(:[], *args, &block)
           ^
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bundler/gems/rubysl-forwardable-4a76567d99e8/lib/rubysl/forwardable/forwardable.rb:192:in `def_instance_delegator'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bundler/gems/rubysl-forwardable-4a76567d99e8/lib/rubysl/forwardable/forwardable.rb:156:in `block in def_instance_delegators'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bundler/gems/rubysl-forwardable-4a76567d99e8/lib/rubysl/forwardable/forwardable.rb:155:in `each'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bundler/gems/rubysl-forwardable-4a76567d99e8/lib/rubysl/forwardable/forwardable.rb:155:in `def_instance_delegators'
	from /home/travis/build/Zrp200/linear/lib/linear/system.rb:6:in `<class:System>'
	from /home/travis/build/Zrp200/linear/lib/linear/system.rb:4:in `<module:Linear>'
	from /home/travis/build/Zrp200/linear/lib/linear/system.rb:3:in `<top (required)>'
	from /home/travis/build/Zrp200/linear/lib/linear/graph.rb:2:in `require'
	from /home/travis/build/Zrp200/linear/lib/linear/graph.rb:2:in `<top (required)>'
	from /home/travis/build/Zrp200/linear/spec/lib/linear/graph_spec.rb:1:in `require'
	from /home/travis/build/Zrp200/linear/spec/lib/linear/graph_spec.rb:1:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bin/rspec:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bin/rspec:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by YorickPeterse** [comment]
The collection of rubysl Gems are not meant for MRI (your stacktrace indicates you're using `ruby-2.0.0-p598`), instead they are to be used on Rubinius only (at least for the time being).

**Comment by marcandre** [comment]
> The collection of rubysl Gems are not meant for MRI.

FWIW, and with all due respect, I think that's just insane.

Moreover that contradicts the [official doc](https://rubygems.org/gems/rubysl):
> Rubysl: Ruby 2.0+ standard library meta-spec. Install this spec to install the Ruby standard library on compliant Ruby implementations that provide Ruby 2.0+ compatibility

**Comment by marcandre** [comment]
Oups, I thought this was about the specs, not the lib itself, sorry.

**Comment by marcandre** [comment]
Does anybody knows how come including a lib in MRI produces a syntax error, when it's meant for implementations that are MRI compatible?

**Comment by brixen** [comment]
@marcandre looks like you may have deleted your comment because I'm not seeing it here, but I'd like to address it

>>    The collection of rubysl Gems are not meant for MRI.

> FWIW, and with all due respect, I think that's just insane.

> Moreover that contradicts the official doc:

>>    Rubysl: Ruby 2.0+ standard library meta-spec. Install this spec to install the Ruby standard library on compliant Ruby implementations that provide Ruby 2.0+ compatibility

If someone wants to fix issues so these gems will load in MRI, they are welcome to do so, including sending PRs. However, that's not an activity that contributors to RubySL would find useful since MRI is extremely unlikely to use anything from RubySL as they are randomly gemifying stuff independently. Perhaps if you resolved that issue, it would be useful to expend effort getting RubySL to work with MRI.

**Comment by YorickPeterse** [comment]
@marcandre The following code breaks: https://github.com/rubysl/rubysl-forwardable/blob/4a76567d99e8fce3e4ce26fe64246f2864b4e7af/lib/rubysl/forwardable/forwardable.rb#L183

This most likely breaks because `accessor` is not set for some reason, leading to just `.__send__(...)` which is not valid Ruby syntax.
